version: '3.2'
services:
  admin:
    image: curity.azurecr.io/curity/idsvr
    # command: ["sh", "-c", "idsvr -s admin"]
    ports:
      - 6749:6749
      - 6789:6789
      - 8443:8443
    environment:
      # - SERVICE_ROLE=admin
      - SERVICE_ROLE=default
      - PASSWORD=Password1
    volumes:
      - ./idsvr/license.json:/opt/idsvr/etc/init/license/license.json
      - ./idsvr/cluster-conf.xml:/opt/idsvr/etc/init/cluster-conf.xml
    networks:
      - net
  # runtime:
  #   image: curity.azurecr.io/curity/idsvr
  #   volumes:
  #     - ./idsvr/license.json:/opt/idsvr/etc/init/license/license.json
  #     - ./idsvr/cluster-conf.xml:/opt/idsvr/etc/init/cluster-conf.xml
  #   environment:
  #     - SERVICE_ROLE=default
  #     - ADMIN_HOSTNAME_OR_IP=curity.local
  #   ports:
  #     - 8443:8443
  #   depends_on:
  #     - admin
  #   networks:
  #     - net
networks:
  net: